# Generated by Django 5.0.2 on 2024-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_stream_auction_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="is_live_auction",
            field=models.BooleanField(default=False),
        ),
    ]
