# Generated by Django 5.0.2 on 2024-02-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_auction_is_live_auction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="twitch_stream_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
