# Generated by Django 5.0.2 on 2024-02-23 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_stream_twitch_stream_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="image",
        ),
    ]
