# Generated by Django 5.0.2 on 2024-02-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_auction_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="image_upload",
            field=models.ImageField(blank=True, null=True, upload_to="auction_images/"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="auctions.category",
            ),
        ),
    ]
