# Generated by Django 5.0.2 on 2024-03-04 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_auction_image_upload_alter_auction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="end_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 11, 16, 31, 39, 182765, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
