# Generated by Django 5.0.2 on 2024-03-04 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_auction_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="end_time",
        ),
        migrations.AddField(
            model_name="auction",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
